version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: progatepass
    volumes:
      - ./db/psgl:/var/lib/postgresql/data
volumes:
  postgres:
